# Generated by Django 5.0.6 on 2024-12-06 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='square_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Square顧客ID'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=128, verbose_name='カード名義')),
                ('brand', models.CharField(max_length=50, verbose_name='カードブランド')),
                ('last_4', models.CharField(max_length=4, verbose_name='カード番号下4桁')),
                ('exp_month', models.IntegerField(verbose_name='有効期限（月）')),
                ('exp_year', models.IntegerField(verbose_name='有効期限（年）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Card',
            },
        ),
    ]
