# Generated by Django 5.0.6 on 2025-01-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.FloatField(default=0.1, verbose_name='割引率')),
                ('description', models.CharField(max_length=256, verbose_name='クーポン説明')),
                ('expiration_date', models.DateField(verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurant.restaurant', verbose_name='対象店舗')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.coupon', verbose_name='クーポン'),
        ),
        migrations.CreateModel(
            name='UsedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用日時')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.coupon', verbose_name='クーポン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'UsedCoupons',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
