# Generated by Django 5.0.6 on 2025-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_coupon_reservation_coupon_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='割引額'),
        ),
    ]
