# Generated by Django 5.0.6 on 2025-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_is_coupon_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_coupon_applied',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_coupon_applied',
            field=models.BooleanField(default=False, verbose_name='クーポン適用'),
        ),
    ]
